services:
  odoo:
    restart: always
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: ./.resources/Dockerfile
    command: odoo --dev=all
    image: local_odoo:${ODOO_MINOR}
    volumes:
      - odoo-web:/var/lib/odoo
      - ./src:/home/odoo/src
      - ./.resources/.coveragerc:/home/odoo/.coveragerc
      - odoo_data:/home/odoo/data
      - py3:/usr/local/lib/
      - py:/usr/lib/
    environment:
      CUSTOM_CONFIG: |-
        [options]
      CUSTOM_REQUIREMTNS: |-
        # custom pip librearies
      CUSTOM_ENTRYPOINT: |-
        #!/bin/bash
        # pip install --user --no-cache-dir -e /home/odoo/custom/odoo
        # pip install --user --no-cache-dir pyopenssl
      # Hardcoded ports
      GEVENT_PORT: 8071 # No cambiar, Nginx lo redirige internamente. Usado para longpolling (Websockets) cuando hay mas de 1 worker
      # Postgres
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${EXTERNAL_PORT_POSTGRES}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${EXTERNAL_PORT_POSTGRES}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # Odoo
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025
      DBFILTER: ${DBFILTER}
      SERVER_WIDE_MODULES: ${SERVER_WIDE_MODULES}
      WORKERS: ${WORKERS}
      LIST_DB: ${LIST_DB}
      WITHOUT_DEMO: ${WITHOUT_DEMO}
      PROXY_MODE: ${PROXY_MODE}
      SERVER_MODE: ${SERVER_MODE}
      AEROO_DOCS_HOST: ${AEROO_DOCS_HOST}
      UNACCENT: ${UNACCENT}
      LOG_LEVEL: info
      # Performance tuning
      LIMIT_MEMORY_SOFT: ${LIMIT_MEMORY_SOFT}
      LIMIT_MEMORY_HARD: ${LIMIT_MEMORY_HARD}
      MAX_CRON_THREADS: ${MAX_CRON_THREADS}
      LIMIT_TIME_REAL_CRON: ${LIMIT_TIME_REAL_CRON}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
      DB_MAXCONN: ${DB_MAXCONN}
    dns:
      - 172.20.${ODOO_MINOR}.10
    networks:
      binaural:
  nginx:
    restart: always
    container_name: ${PROJECT_NAME}-nginx
    image: nginx:latest
    ports:
      - "${EXTERNAL_PORT_ODOO}:80"
    volumes:
      - ./.resources/nginx_configs/odoo.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - odoo
    networks:
      binaural:

volumes:
  odoo-web:
  odoo_data:
  py3:
  py:
  odoo-pgadmin:

networks:
  binaural:
    driver: bridge
    external: false
    name: odoo-${ODOO_VERSION}
    ipam:
      config:
        - subnet: 172.20.${ODOO_MINOR}.0/24
