services:
  db:
    image: local_db:16.0
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data
    networks:
      - binaural
    deploy:
      placement:
        constraints:
          - node.labels.role == db_node
      restart_policy:
        condition: on-failure
  odoo:
    image: local_odoo:18.0
    ports:
      - "80:8069"
    volumes:
      - odoo-web:/var/lib/odoo
      - ./src:/home/odoo/src
      - ./.resources/.coveragerc:/home/odoo/.coveragerc
      - odoo_data:/home/odoo/data
      - py3:/usr/local/lib/
      - py:/usr/lib/
    command: odoo server --dev=all
    labels:
      - traefik.enable=true
      - traefik.http.port=8069
      - traefik.http.rule=HostRegexp:$DOMAIN,{subdomain:[a-z0-9-_]+}.$DOMAIN
      # - traefik.http.priority=10
      # - traefik.longpolling.port=8072
      # - traefik.longpolling.frontend.rule=HostRegexp:$DOMAIN,{subdomain:[a-z0-9-_]+}.$DOMAIN;PathPrefix:/longpolling/
      - traefik.backend.loadbalancer.stickiness=true
      - traefik.backend.loadbalancer.method=drr
      # traefik.http.redirect.regex: $strTraefikRedirectRegex
      # traefik.http.redirect.replacement: $strTraefikRedirectReplacement
    environment:
      CUSTOM_CONFIG: |-
        [options]
      CUSTOM_REQUIREMTNS: |-
        # custom pip librearies
      CUSTOM_ENTRYPOINT: |-
        #!/bin/bash
        # pip install --user --no-cache-dir -e /home/odoo/custom/odoo
        # pip install --user --no-cache-dir pyopenssl
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025
      DBFILTER:
      SERVER_WIDE_MODULES:
      MAX_CRON_THREADS: 0
      WORKERS: 0
      LIST_DB: 1
      WITHOUT_DEMO: 0
      ADMIN_PASSWORD: admin
      PROXY_MODE: 1
      SERVER_MODE: test
      AEROO_DOCS_HOST: aeroo
      LIMIT_TIME_REAL_CRON: 0
      LIMIT_TIME_REAL: 999999999999
      UNACCENT: 0
      LOG_LEVEL: info
    networks:
      - binaural
    deploy:
      placement:
        constraints:
          - node.labels.role == leader_node
      restart_policy:
        condition: on-failure

volumes:
  odoo-db:
  odoo-web:
  odoo_data:
  py3:
  py:
  odoo-pgadmin:

networks:
  binaural:
    driver: overlay
    # external: false
    # ipam:
    #   config:
    #     - subnet: 172.20.18.0/24
