services:
  db:
    command: ["postgres", "-c", "config_file=/etc/postgres/dbconfigs/postgresql.conf"]
    restart: always
    container_name: ${PROJECT_NAME}_db
    build:
      context: .
      dockerfile: ./.resources/db.Dockerfile
      args:
        POSTGRES_IMG_VERSION: ${POSTGRES_IMG_VERSION}
    image: local_odoo_db_${PROJECT_NAME}:${POSTGRES_IMG_VERSION}
    ports:
      - "${EXTERNAL_PORT_POSTGRES}:5432"
    networks:
      - binaural
    volumes:
      - ./.resources/dbconfigs:/etc/postgres/dbconfigs
      - odoo-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
volumes:
  odoo-db:

networks:
  binaural:
    driver: bridge
    external: false
    name: ${PROJECT_NAME}-odoo-${ODOO_VERSION}
