services:
  traefik:
    container_name: ${PROJECT_NAME}_traefik
    image: traefik:latest
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    labels:
      - traefik.enable=true
      - traefik.port=8080
      - traefik.frontend.rule=Host:traefik.localhost
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    # para que funcione la soluci√≥n *.localhost
    # network_mode: "host"
    ports:
      - "${TRAEFIK_HOST_PORT}:${TRAEFIK_SERVICE_CONTAINER_PORT}"
    networks:
      - binaural
    restart: always
  dns:
    image: cytopia/bind:alpine-0.30
    environment:
      DNS_A: "*.odoo.localhost=172.20.${ODOO_MINOR}.1"
      DNS_FORWARDER: 127.0.0.11
    networks:
      binaural:
        ipv4_address: 172.20.${ODOO_MINOR}.10
    restart: always
  odoo:
    container_name: ${PROJECT_NAME}
    build:
      context: .
      dockerfile: ./.resources/Dockerfile
    ports:
      - "${PORT_SERVICE_HOST_ODOO}:${PORT_SERVICE_CONTAINER_ODOO}"
      - "${LONGPOLLING_PORT}:${LONGPOLLING_PORT}"
    depends_on:
      - dns
      - traefik
    volumes:
      - odoo-web:/var/lib/odoo
      - ./src:/home/odoo/src
      - ./.resources/.coveragerc:/home/odoo/.coveragerc
      - odoo_data:/home/odoo/data
      - py3:/usr/local/lib/
      - py:/usr/lib/
    command: odoo --dev=all
    labels:
      - traefik.enable=true
      - traefik.frontend.port=8069
      - traefik.frontend.rule=HostRegexp:$DOMAIN,{subdomain:[a-z0-9-_]+}.$DOMAIN
      # - traefik.frontend.priority=10
      # - traefik.longpolling.port=8072
      # - traefik.longpolling.frontend.rule=HostRegexp:$DOMAIN,{subdomain:[a-z0-9-_]+}.$DOMAIN;PathPrefix:/longpolling/
      - traefik.backend.loadbalancer.stickiness=true
      - traefik.backend.loadbalancer.method=drr
      # traefik.frontend.redirect.regex: $strTraefikRedirectRegex
      # traefik.frontend.redirect.replacement: $strTraefikRedirectReplacement
    environment:
      CUSTOM_CONFIG: |-
        [options]
      CUSTOM_REQUIREMTNS: |-
        # custom pip librearies
      CUSTOM_ENTRYPOINT: |-
        #!/bin/bash
        # pip install --user --no-cache-dir -e /home/odoo/custom/odoo
        # pip install --user --no-cache-dir pyopenssl
      # Postgres
      DB_HOST: ${POSTGRES_HOST}
      DB_PORT: ${POSTGRES_PORT}
      PGUSER: ${POSTGRES_USER}
      PGPASSWORD: ${POSTGRES_PASSWORD}
      PGHOST: ${POSTGRES_HOST}
      PGPORT: ${POSTGRES_PORT}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      # Odoo
      SMTP_SERVER: mailhog
      SMTP_PORT: 1025
      DBFILTER: ${DBFILTER}
      SERVER_WIDE_MODULES: ${SERVER_WIDE_MODULES}
      WORKERS: ${WORKERS}
      LIST_DB: ${LIST_DB}
      WITHOUT_DEMO: ${WITHOUT_DEMO}
      PROXY_MODE: ${PROXY_MODE}
      SERVER_MODE: ${SERVER_MODE}
      AEROO_DOCS_HOST: ${AEROO_DOCS_HOST}
      LONGPOLLING_PORT: ${LONGPOLLING_PORT}
      GEVENT_PORT: ${GEVENT_PORT}
      UNACCENT: ${UNACCENT}
      LOG_LEVEL: info
      # Performance tuning
      LIMIT_MEMORY_SOFT: ${LIMIT_MEMORY_SOFT}
      LIMIT_MEMORY_HARD: ${LIMIT_MEMORY_HARD}
      MAX_CRON_THREADS: ${MAX_CRON_THREADS}
      LIMIT_TIME_REAL_CRON: ${LIMIT_TIME_REAL_CRON}
      LIMIT_TIME_REAL: ${LIMIT_TIME_REAL}
      DB_MAXCONN: ${DB_MAXCONN}
    dns:
      - 172.20.${ODOO_MINOR}.10
    networks:
      binaural:
    restart: always

volumes:
  odoo-web:
  odoo_data:
  py3:
  py:
  odoo-pgadmin:

networks:
  binaural:
    driver: bridge
    external: false
    name: odoo-${ODOO_VERSION}
    ipam:
      config:
        - subnet: 172.20.${ODOO_MINOR}.0/24
