services:
  db:
    build:
      context: .
      dockerfile: ./.resources/db.Dockerfile
      args:
        POSTGRES_IMG_VERSION: ${POSTGRES_IMG_VERSION}
    container_name: ${PROJECT_NAME}_db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db:/var/lib/postgresql/data
    networks:
      - binaural
    restart: always

volumes:
  odoo-db:

networks:
  binaural:
    driver: bridge
    external: false
    name: odoo-${ODOO_VERSION}
    ipam:
      config:
        - subnet: 172.20.${ODOO_MINOR}.0/24
